# Generated by Django 3.0.3 on 2020-02-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data2',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
