# Generated by Django 3.0.3 on 2020-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttons',
            name='button1',
            field=models.BooleanField(default=False),
        ),
    ]
