# Generated by Django 3.0.3 on 2020-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20200220_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button1', models.CharField(default='0', max_length=10)),
                ('button2', models.CharField(default='0', max_length=10)),
                ('button3', models.CharField(default='0', max_length=10)),
                ('button4', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='button1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='button2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='button3',
        ),
        migrations.RemoveField(
            model_name='data',
            name='button4',
        ),
    ]
