# Generated by Django 3.0.3 on 2020-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20200220_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='button1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='button',
            name='button2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='button',
            name='button3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='button',
            name='button4',
            field=models.CharField(max_length=10),
        ),
    ]
